### PR TITLE
Yunchao/upcoming future date only

### LINKED ISSUE #74: bug: upcoming shouldnt accept a date and time that is has passed
- to prevent "expired" upcomings from being shown in the upcoming list

- [ ] update test cases & default people to also have upcomings that are far into the future to prevent unexpected bugs

### PR DESCRIPTION
**Pull request by tanyunchao**
fixes #74 
- Added additional check for dates to be after now() before being initiated as an Upcoming
- Edited `LastContact.java` to use isBefore instead of !isAfter
- Updated dummy test data

### CODE REVIEW

File: src/test/java/seedu/address/model/person/UpcomingTest.java [hunk 1]
```diff
@@ -157,7 +157,7 @@ public void toString_noUpcoming_returnsEmptyString() {
 
     @Test
     public void hasUpcoming_true() {
-        Upcoming upcoming = new Upcoming("01-01-2022 1200");
+        Upcoming upcoming = new Upcoming("01-01-2025 1200");
```
Comment (ziyang27) [inline src/test/java/seedu/address/model/person/UpcomingTest.java:160]: Thank you for updating the dates 👍

File: src/main/java/seedu/address/model/person/LastContact.java [hunk 2]
```diff
@@ -52,7 +52,7 @@ public static boolean isValidDateTime(String dateTime) {
         String trimmedDateTime = dateTime.trim();
         try {
             LocalDateTime parsedDateTime = LocalDateTime.parse(trimmedDateTime, DATETIME_FORMATTER);
-            return !parsedDateTime.isAfter(LocalDateTime.now()); // Successfully parsed, input matches the format
+            return parsedDateTime.isBefore(LocalDateTime.now()); // Successfully parsed, input matches the format
```
Comment (ziyang27) [inline src/main/java/seedu/address/model/person/LastContact.java:55]: Good use of comment 😄

**Review by ziyang27 — COMMENTED** [review]
LTGM 🐳

**Review by ziyang27 — APPROVED** [review]
LGTM 👍
